#!/usr/bin/env python3
"""Package and optionally upload HyperCubeServer from outside Minecraft."""

from __future__ import annotations

import argparse
import math
import re
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:  # pragma: no cover - only hit when requests is not installed.
    requests = None


OUTPUT_FILE = "hypercube_server_pastebin.lua"
CHUNK_SIZE = 240000
BATCH_INSTALL_FILE = "hypercube_server_pastebin_batch_install.lua"

INCLUDE_ROOTS = [
    "Kernal",
    "appstore",
    "installer",
    "docs",
    "init.lua",
    "startup.lua",
    "README.md",
    "checklist.md",
    "update_server.lua",
]

EXCLUDE = {
    OUTPUT_FILE,
    "logs",
    "user",
    "hypercube_db",
    "package_server.lua",
    "package_server.py",
    "pastebin_dev_key",
    "pastebin_dev_key.lua",
}


def output_part_name(index: int) -> str:
    return f"hypercube_server_pastebin_chunk_{index:02d}.lua"


def output_install_name() -> str:
    return "hypercube_server_pastebin_install.lua"


def normalize(path: str | Path) -> str:
    return str(path).replace("\\", "/").lstrip("./").lstrip("/")


def is_excluded(path: str) -> bool:
    path = normalize(path)
    if path in EXCLUDE:
        return True
    return any(path.startswith(excluded + "/") for excluded in EXCLUDE)


def lua_quote_bytes(data: bytes) -> str:
    out: list[str] = ['"']
    for byte in data:
        if byte == 34:
            out.append('\\"')
        elif byte == 92:
            out.append("\\\\")
        elif byte == 10:
            out.append("\\n")
        elif byte == 13:
            out.append("\\r")
        elif byte == 9:
            out.append("\\t")
        elif 32 <= byte <= 126:
            out.append(chr(byte))
        else:
            out.append(f"\\{byte:03d}")
    out.append('"')
    return "".join(out)


def lua_quote_text(text: str) -> str:
    return lua_quote_bytes(text.encode("utf-8"))


def cleanup_outputs(root: Path) -> None:
    for name in [OUTPUT_FILE, output_install_name(), BATCH_INSTALL_FILE]:
        path = root / name
        if path.exists():
            path.unlink()
    for index in range(1, 100):
        path = root / output_part_name(index)
        if path.exists():
            path.unlink()


def collect_tree(root: Path, relative: str, files: list[dict[str, object]]) -> None:
    relative = normalize(relative)
    if is_excluded(relative):
        return

    path = root / relative
    if path.is_dir():
        for child in sorted(path.iterdir(), key=lambda item: item.name):
            child_relative = child.relative_to(root).as_posix()
            collect_tree(root, child_relative, files)
        return

    data = path.read_bytes()
    files.append({
        "path": relative,
        "data": data,
        "size": len(data),
    })


def collect(root: Path) -> list[dict[str, object]]:
    files: list[dict[str, object]] = []
    for include in INCLUDE_ROOTS:
        if (root / include).exists():
            collect_tree(root, include, files)
    files.sort(key=lambda file: str(file["path"]))
    return files


def installer_source(files: list[dict[str, object]]) -> str:
    lines = [
        "-- HyperCubeServer pastebin installer",
        "-- Generated by package_server.py",
        "local PACKAGE = {",
        '  name = "HyperCubeServer",',
        f"  generated_at = {int(time.time() * 1000)},",
        "  files = {",
    ]

    for file in files:
        lines.append(
            "    { path = "
            + lua_quote_text(str(file["path"]))
            + ", data = "
            + lua_quote_bytes(file["data"])  # type: ignore[arg-type]
            + " },"
        )

    lines.extend([
        "  },",
        "}",
        r'''

local CLEAN_PATHS = {
  "Kernal",
  "appstore",
  "installer",
  "docs",
  "init.lua",
  "startup.lua",
  "README.md",
  "checklist.md",
  "update_server.lua",
}

local function ensure_parent(path)
  local dir = path:match("^(.*)/[^/]+$")
  if dir and dir ~= "" and not fs.exists(dir) then
    fs.makeDir(dir)
  end
end

local function write_file(path, data)
  ensure_parent(path)
  local handle = fs.open(path, "wb")
  if not handle then
    error("Failed to open " .. tostring(path))
  end
  handle.write(data)
  handle.close()
end

term.clear()
term.setCursorPos(1, 1)
print("HyperCubeServer installer")
print("Files: " .. tostring(#PACKAGE.files))
print("")
write("Install/overwrite this computer? [y/N] ")
local answer = read()
if tostring(answer or ""):lower() ~= "y" then
  print("Cancelled.")
  return
end

for _, path in ipairs(CLEAN_PATHS) do
  if fs.exists(path) then
    fs.delete(path)
  end
end

for i, file in ipairs(PACKAGE.files) do
  write_file(file.path, file.data)
  if i % 10 == 0 then
    print("Installed " .. tostring(i) .. "/" .. tostring(#PACKAGE.files))
  end
end

local handle = fs.open("hypercube_server_install", "w")
if handle then
  handle.write(textutils.serialize({
    os = PACKAGE.name,
    installed_at = os.epoch and os.epoch("utc") or os.clock(),
    files = #PACKAGE.files,
    source = "pastebin",
  }))
  handle.close()
end

print("HyperCubeServer installed.")
print("Run 'reboot' or restart this computer.")
''',
    ])
    return "\n".join(lines)


def chunk_bootstrap_source(chunk_count: int) -> str:
    return f'''-- HyperCubeServer chunked pastebin installer
-- Generated by package_server.py
local PACKAGE_NAME = "HyperCubeServer"
local CHUNK_COUNT = {chunk_count}

local function load_lua(source, name, env)
  env = env or _G
  if load then
    local ok, loader_or_err = pcall(load, source, name, "t", env)
    if ok and loader_or_err then
      if setfenv then setfenv(loader_or_err, env) end
      return loader_or_err
    end
    if ok and type(loader_or_err) == "string" then
      return nil, loader_or_err
    end
  end
  if loadstring then
    local loader, err = loadstring(source, name)
    if not loader then return nil, err end
    if setfenv then setfenv(loader, env) end
    return loader
  end
  return nil, "NoLoader"
end

local function read_code(index)
  write("Pastebin code for chunk " .. tostring(index) .. "/" .. tostring(CHUNK_COUNT) .. ": ")
  local code = read()
  code = tostring(code or ""):match("^%s*(.-)%s*$")
  if code == "" then
    error("Missing code for chunk " .. tostring(index))
  end
  return code
end

local function fetch_chunk(index, code)
  if not http or not http.get then
    error("HTTP API is required to fetch pastebin chunks")
  end
  local url = "https://pastebin.com/raw/" .. tostring(code)
  local response, err = http.get(url)
  if not response then
    error("Chunk " .. tostring(index) .. " download failed: " .. tostring(err))
  end
  local source = response.readAll()
  response.close()
  local loader, load_err = load_lua(source, "@chunk_" .. tostring(index), {{}})
  if not loader then
    error("Chunk " .. tostring(index) .. " load failed: " .. tostring(load_err))
  end
  local ok, data = pcall(loader)
  if not ok then
    error("Chunk " .. tostring(index) .. " returned error: " .. tostring(data))
  end
  if type(data) ~= "string" then
    error("Chunk " .. tostring(index) .. " did not return string data")
  end
  return data
end

term.clear()
term.setCursorPos(1, 1)
print(PACKAGE_NAME .. " chunked installer")
print("Chunks required: " .. tostring(CHUNK_COUNT))
print("Upload all chunk files first with pastebin put, then enter each code here.")
print("")

local chunks = {{}}
for i = 1, CHUNK_COUNT do
  chunks[i] = fetch_chunk(i, read_code(i))
  print("Fetched chunk " .. tostring(i) .. "/" .. tostring(CHUNK_COUNT))
end

local installer_source = table.concat(chunks)
local installer, err = load_lua(installer_source, "@hypercube_server_combined", _G)
if not installer then
  error("Combined installer failed to load: " .. tostring(err))
end
return installer()
'''


def batch_install_source(codes: list[str]) -> str:
    encoded = ", ".join(lua_quote_text(code) for code in codes)
    return f'''-- HyperCubeServer batch pastebin installer
-- Generated by package_server.py
local PACKAGE_NAME = "HyperCubeServer"
local CHUNK_CODES = {{ {encoded} }}

local function load_lua(source, name, env)
  env = env or _G
  if load then
    local ok, loader_or_err = pcall(load, source, name, "t", env)
    if ok and loader_or_err then
      if setfenv then setfenv(loader_or_err, env) end
      return loader_or_err
    end
    if ok and type(loader_or_err) == "string" then
      return nil, loader_or_err
    end
  end
  if loadstring then
    local loader, err = loadstring(source, name)
    if not loader then return nil, err end
    if setfenv then setfenv(loader, env) end
    return loader
  end
  return nil, "NoLoader"
end

local function fetch_chunk(index, code)
  if not http or not http.get then
    error("HTTP API is required to fetch pastebin chunks")
  end
  local url = "https://pastebin.com/raw/" .. tostring(code)
  local response, err = http.get(url)
  if not response then
    error("Chunk " .. tostring(index) .. " download failed: " .. tostring(err))
  end
  local source = response.readAll()
  response.close()
  local loader, load_err = load_lua(source, "@chunk_" .. tostring(index), {{}})
  if not loader then
    error("Chunk " .. tostring(index) .. " load failed: " .. tostring(load_err))
  end
  local ok, data = pcall(loader)
  if not ok then
    error("Chunk " .. tostring(index) .. " returned error: " .. tostring(data))
  end
  if type(data) ~= "string" then
    error("Chunk " .. tostring(index) .. " did not return string data")
  end
  return data
end

term.clear()
term.setCursorPos(1, 1)
print(PACKAGE_NAME .. " batch installer")
print("Chunks: " .. tostring(#CHUNK_CODES))
print("")

local chunks = {{}}
for i, code in ipairs(CHUNK_CODES) do
  chunks[i] = fetch_chunk(i, code)
  print("Fetched chunk " .. tostring(i) .. "/" .. tostring(#CHUNK_CODES))
end

local installer_source = table.concat(chunks)
local installer, err = load_lua(installer_source, "@hypercube_server_combined", _G)
if not installer then
  error("Combined installer failed to load: " .. tostring(err))
end
return installer()
'''


def write_chunked_outputs(root: Path, source: str) -> list[Path]:
    chunks: list[Path] = []
    source_bytes = source.encode("utf-8")
    for index, start in enumerate(range(0, len(source_bytes), CHUNK_SIZE), start=1):
        chunk = source_bytes[start:start + CHUNK_SIZE]
        path = root / output_part_name(index)
        path.write_text("return " + lua_quote_bytes(chunk) + "\n", encoding="utf-8", newline="\n")
        chunks.append(path)

    install_path = root / output_install_name()
    install_path.write_text(chunk_bootstrap_source(len(chunks)), encoding="utf-8", newline="\n")
    return [install_path, *chunks]


def pastebin_code_from_text(text: str) -> str | None:
    patterns = [
        r"pastebin\.com/raw/([\w_-]+)",
        r"pastebin\.com/([\w_-]+)",
        r"code:\s*([\w_-]+)",
        r"Code:\s*([\w_-]+)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return match.group(1)
    return None


def read_dev_key(root: Path, args: argparse.Namespace) -> str | None:
    if args.dev_key:
        return args.dev_key.strip()
    for name in ["pastebin_dev_key"]:
        path = root / name
        if path.exists():
            return path.read_text(encoding="utf-8").strip()
    return None


def upload_with_api(path: Path, dev_key: str, args: argparse.Namespace) -> tuple[str, str]:
    if requests is None:
        raise RuntimeError("Python package 'requests' is required for --upload. Install it with: python3 -m pip install requests")

    fields = {
        "api_dev_key": dev_key,
        "api_option": "paste",
        "api_paste_code": path.read_text(encoding="utf-8"),
        "api_paste_name": path.name,
        "api_paste_private": args.private,
        "api_paste_expire_date": args.expire,
        "api_paste_format": "lua",
    }
    if args.user_key:
        fields["api_user_key"] = args.user_key

    headers = {
        "User-Agent": args.user_agent,
        "Accept": "text/plain, */*;q=0.8",
        "Origin": "https://pastebin.com",
        "Referer": "https://pastebin.com/",
    }

    session = requests.Session()
    response = session.post(
        "https://pastebin.com/api/api_post.php",
        data=fields,
        headers=headers,
        timeout=args.timeout,
    )
    text = response.text

    if response.status_code == 403:
        raise RuntimeError(
            "Pastebin returned HTTP 403. This is usually Cloudflare/API blocking, "
            "an invalid dev key, or a paste privacy/user-key mismatch. Response: "
            + text[:300]
        )
    if response.status_code >= 400:
        raise RuntimeError(f"Pastebin returned HTTP {response.status_code}: {text[:300]}")

    if text.startswith("Bad API request"):
        raise RuntimeError(text)
    code = pastebin_code_from_text(text)
    if not code:
        raise RuntimeError("PastebinCodeNotFound: " + text)
    return code, text


def upload_batch_install_streaming(root: Path, source: str, args: argparse.Namespace) -> dict[str, object]:
    dev_key = read_dev_key(root, args)
    if not dev_key:
        raise RuntimeError("Pastebin dev key required: pass --dev-key or create pastebin_dev_key")

    codes: list[str] = []
    source_bytes = source.encode("utf-8")
    total_chunks = math.ceil(len(source_bytes) / CHUNK_SIZE)

    for index in range(1, total_chunks + 1):
        start = (index - 1) * CHUNK_SIZE
        chunk = source_bytes[start:start + CHUNK_SIZE]
        path = root / output_part_name(index)
        path.write_text("return " + lua_quote_bytes(chunk) + "\n", encoding="utf-8", newline="\n")

        print(f"Uploading chunk {index}/{total_chunks}: {path.name}")
        try:
            code, _ = upload_with_api(path, dev_key, args)
        finally:
            if not args.keep_chunks and path.exists():
                path.unlink()
        code = code[:8]
        codes.append(code)
        print(f"  code: {code}")

    batch_path = root / BATCH_INSTALL_FILE
    batch_path.write_text(batch_install_source(codes), encoding="utf-8", newline="\n")

    print(f"Uploading batch installer: {BATCH_INSTALL_FILE}")
    final_code, _ = upload_with_api(batch_path, dev_key, args)
    final_code = final_code[:8]
    return {
        "path": BATCH_INSTALL_FILE,
        "code": final_code,
        "chunks": codes,
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Package HyperCubeServer for Pastebin.")
    parser.add_argument("--source-root", default=None, help="Source root to package. Defaults to this script's folder.")
    parser.add_argument("--upload", action="store_true", help="Upload chunks and final batch installer to Pastebin.")
    parser.add_argument("--single", action="store_true", help=f"Write {OUTPUT_FILE}.")
    parser.add_argument("--dev-key", default=None, help="Pastebin API dev key.")
    parser.add_argument("--user-key", default=None, help="Optional Pastebin user key.")
    parser.add_argument("--private", default="1", choices=["0", "1", "2"], help="Pastebin privacy: 0 public, 1 unlisted, 2 private.")
    parser.add_argument("--expire", default="N", help="Pastebin expiration, e.g. N, 1D, 1W, 1M.")
    parser.add_argument("--timeout", type=int, default=60, help="HTTP timeout in seconds.")
    parser.add_argument("--keep-chunks", action="store_true", help="Keep temporary chunk files after --upload.")
    parser.add_argument(
        "--user-agent",
        default="Mozilla/5.0 (Windows NT 10.0; Win64; x64) HyperCubePackager/1.0",
        help="User-Agent header used for Pastebin API uploads.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    root = Path(args.source_root).resolve() if args.source_root else Path(__file__).resolve().parent

    cleanup_outputs(root)
    files = collect(root)
    total = sum(int(file["size"]) for file in files)
    source = installer_source(files)

    print(f"Source root: {root}")
    print(f"Files packed: {len(files)}")
    print(f"Raw bytes: {total}")
    print(f"Installer bytes: {len(source.encode('utf-8'))}")

    if args.upload:
        try:
            result = upload_batch_install_streaming(root, source, args)
        except Exception as exc:
            print(f"Upload failed: {exc}")
            return 1
        print("")
        print(f"Wrote {result['path']}")
        print(f"Final installer Pastebin code: {result['code']}")
        print("Install command:")
        print(f"pastebin run {result['code']}")
        return 0

    if args.single:
        (root / OUTPUT_FILE).write_text(source, encoding="utf-8", newline="\n")
        print(f"Wrote {OUTPUT_FILE}")
    else:
        print(f"Skipping {OUTPUT_FILE} to save disk space. Pass --single to write it.")

    outputs = write_chunked_outputs(root, source)
    print("Pastebin-safe chunk files:")
    for path in outputs:
        print(f"  {path.name} ({path.stat().st_size} bytes)")
    print("Run with --upload to upload chunks and generate a final batch installer code.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
